---
title: "Study 1 condition assignment"
author: "Ian Hussey"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    code_folding: hide
    highlight: haddock
    theme: flatly
    toc: yes
    toc_float: yes
---

```{r, include=FALSE}
knitr::opts_chunk$set(message = FALSE,
                      warning = FALSE)
```

# Dependencies

```{r}

library(tidyverse)
library(knitr)
library(kableExtra)

```

# Seed

```{r}

set.seed(42)

```

# Create condition assignment

```{r}

# generate conditions
dat <- tibble(Condition = c(rep(1, times = 40), rep(2, times = 40)),
              Word = c(rep(1, times = 10), rep(2, times = 10), rep(3, times = 10), rep(4, times = 10),
                       rep(1, times = 10), rep(2, times = 10), rep(3, times = 10), rep(4, times = 10)),
              Order = rep(c(1, 2), times = 40))

# create dependent columns
# ## original english
# dat_annotated <- dat |>
#   mutate(Target = case_when(Word %in% c(1, 2) ~ 1,
#                             Word %in% c(3, 4) ~ 2),
#          condition_printed = case_when(Condition == 1 ~ "try NOT",
#                                        Condition == 2 ~ "try"),
#          word_printed = case_when(Word == 1 ~ "MOUNTAIN",
#                                   Word == 2 ~ "CAR",
#                                   Word == 3 ~ "CHILD",
#                                   Word == 4 ~ "HOUSE"),
#          Instruction = paste0("For your first task, please ", condition_printed, " to think about a ", word_printed, " for the next five minutes. I will be back in five minutes")) |>
#   select(Instruction, Condition, Word, Target, Order, condition_printed, word_printed)

## translated german
dat_annotated <- dat |>
  mutate(Target = case_when(Word %in% c(1, 2) ~ 1,
                            Word %in% c(3, 4) ~ 2),
         condition_printed = case_when(Condition == 1 ~ "NICHT an",
                                       Condition == 2 ~ "an"),
         word_printed = case_when(Word == 1 ~ "einen BERG",
                                  Word == 2 ~ "ein AUTO",
                                  Word == 3 ~ "ein KIND",
                                  Word == 4 ~ "ein HAUS"),
         Instruction = paste0("Versuchen Sie bei Ihrer ersten Aufgabe, in den nächsten fünf Minuten ", condition_printed, " ", word_printed, " zu denken. Ich bin in fünf Minuten zurück.")) |>
  select(Instruction, Condition, Word, Target, Order, condition_printed, word_printed)

 

# print conditions for verification
dat_annotated |>
  count(Condition, Word, Target, Order) |>
  kable() |>
  kable_classic(full_width = FALSE)

# shuffle rows
dat_shuffled <- dat_annotated |>
  dplyr::sample_frac(size = 1) 

# save
write_csv(dat_shuffled, "condition_assignments.csv")

```

