---
title: "Comparing final dataset on OSF with reproduced dataset from code and processed data"
author: "Ian Hussey"
output:
  html_document:
    code_folding: hide
    highlight: haddock
    theme: flatly
    toc: yes
    toc_float: yes
---

```{r include=FALSE}
# formatting options
# set default chunk options
knitr::opts_chunk$set(message = FALSE, 
                      warning = FALSE)

```

# Compare results df on OSF with that reproduced from processed data

```{r}

library(tidyverse)
library(knitr)
library(kableExtra)

df_original <- read_csv("../../data/output/RRR_WE92_all.csv") 

df_reproduced <- read_csv("../../data/output/results_study_1_RRR_WE92_all.csv") |>
  select(any_of(names(df_original)),   # columns in Y's order that exist in X
         everything())        # then all remaining columns

write.csv(df_reproduced, "../../data/output/results_study_1_reordered_RRR_WE92_all.csv") 

diffs <- bind_cols(df_original, df_reproduced, .name_repair = ~ make.unique(.)) %>%
  mutate(across(
    .cols = intersect(names(df_original), names(df_reproduced)),
    .fns = ~ {
      if (is.numeric(df_original[[cur_column()]]) && is.numeric(df_reproduced[[cur_column()]])) {
        df_original[[cur_column()]] - df_reproduced[[cur_column()]]
      } else {
        NA
      }
    },
    .names = "{.col}_diff"
  )) |>
  select(Lab, ends_with("_diff"), -Lab_diff, -Country_diff, -Researcher_diff, -ES.cond_TP_wordtype_replication_diff) 

write.csv(diffs, "../../data/output/results_study_1_reproducibility_diffs.csv") 

diffs |>
  pivot_longer(cols = -Lab,
               names_to = "column", 
               values_to = "diff") |>
  group_by(column) |>
  summarize(max_abs_diff = max(abs(diff), na.rm = TRUE)) |>
  arrange(desc(max_abs_diff)) |>
  kable() |>
  kable_classic(full_width = TRUE)

```

Many cells differ 




